name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip *.zip

      - name: Find project folder
        run: |
          echo "Listing files..."
          ls -R
          FOLDER=$(find . -name "gradlew" -exec dirname {} \;)
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x $FOLDER/gradlew

      - name: Build APK
        run: cd $FOLDER && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ${{ env.FOLDER }}/app/build/outputs/apk/debug/app-debug.apk
